language: php
php:
- 5.6
- 5.5
- 5.4
- 5.3
- '7.0'
install: composer install
before_script:
  - cp phpunit.xml.dist phpunit.xml
  # These two are required in the build step for non-composer-tests
  - mkdir -p libs
  - cd libs &&  wget https://github.com/rmccue/Requests/archive/v1.6.1.zip -O requests.zip && unzip requests.zip && rm requests.zip && cd ..
script:
  - phpunit

notifications:
  slack:
    secure:
# We are doing the releases for non-composer folks
# So this includes the vendor directory
before_deploy:
  - echo $TRAVIS_TAG > version.txt
  - cat release.txt |zip -r@ "razorpay-php.zip"
deploy:
  provider: releases
  # Otherwise, we lose the vendor/ directory
  skip_cleanup: true
  api_key:
    secure:
  # travis doesn't support multi file deployes yet, not that we need them
  file: razorpay-php.zip
  on:
    # Only do the release for one build every tag
    php: 5.6
    # GitHub refuses to accept releases that are not tagged
    tags: true
    # Allow builds for non-master branches as well
    all_branches: true
    # Only do the releases if the repo is not a fork
    repo: razorpay/razorpay-php
